### ISSUE TITLE
vc-provider-imagery-supermap移除时报错

### ISSUE THREAD

**Issue by JennicaLi** [zouyaoji/vue-cesium-v2#1]
### 浏览器版本号

Chrome 91.0.4472.124

### Vue 版本号

2.6.11

### 组件库版本号

2.2.3

### 现象描述

```
使用数组v-for控制多个图层的显示，当用splice更新数组后，缩放图层，弹出cesium-widget报错框；v2.1.8版本没有问题
```

### 完整异常信息

```
An error occurred while rendering. Rendering has stopped.
DeveloperError: This object was destroyed, i.e., destroy() was called.
Error
    at new r (eval at <anonymous> (http://localhost:8080/libs/Cesium/Cesium.js:25:1), <anonymous>:1:12755)
    at Ac.c (eval at <anonymous> (http://localhost:8080/libs/Cesium/Cesium.js:25:1), <anonymous>:1:54610)
    at Ri.releaseReference (eval at <anonymous> (http://localhost:8080/libs/Cesium/Cesium.js:25:1), <anonymous>:1:3252462)
    at UC.freeResources (eval at <anonymous> (http://localhost:8080/libs/Cesium/Cesium.js:25:1), <anonymous>:1:3914765)
    at Ge.freeResources (eval at <anonymous> (http://localhost:8080/libs/Cesium/Cesium.js:25:1), <anonymous>:1:4620437)
    at Wg.freeResources (eval at <anonymous> (http://localhost:8080/libs/Cesium/Cesium.js:25:1), <anonymous>:1:4708830)
    at YJ (eval at <anonymous> (http://localhost:8080/libs/Cesium/Cesium.js:25:1), <anonymous>:1:1184877)
    at Wg.freeResources (eval at <anonymous> (http://localhost:8080/libs/Cesium/Cesium.js:25:1), <anonymous>:1:4708899)
    at pB.trimTiles (eval at <anonymous> (http://localhost:8080/libs/Cesium/Cesium.js:25:1), <anonymous>:1:1855276)
    at Pk.endFrame (eval at <anonymous> (http://localhost:8080/libs/Cesium/Cesium.js:25:1), <anonymous>:1:4718027)
```

### 在线示例 / 仓库 URL

无

### 复现代码

```
<template>
  <div class="viewer">
    <vc-viewer @ready="ready" :infoBox="false">
      <vc-layer-imagery v-for="layer in layerList" :key="layer.id">
        <vc-provider-imagery-supermap @readyPromise="readyPromise"
          v-if="layer.type === 'supermap'" ref="imageryProvider"
          :url="layer.options.url"
        ></vc-provider-imagery-supermap>
      </vc-layer-imagery>
    </vc-viewer>
    <div class="demo-tool">
      <a-button type="primary" @click="removeLayer">去除图层</a-button>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      layerList: [
        {
          id: 1,
          type: 'supermap',
          options: {
            url:
              'http://www.supermapol.com/realspace/services/map-China400/rest/maps/China400',
            name: '图层1',
          },
        },
        {
          id: 2,
          type: 'supermap',
          options: {
            url:
              'http://www.supermapol.com/realspace/services/map-World/rest/maps/World_Google',
            name: '图层2',
          },
        },
      ],
    }
  },
  methods: {
    readyPromise() {
        // const {  viewer } = this.cesiumInstance
        // viewer.zoomTo(this.$refs.imageryProvider.providerContainer.imageryLayer)
      },
    removeLayer() {
      if (this.layerList.length > 0) {
        this.layerList.splice(0, 1)
      }
    },
    ready(cesiumInstance) {
      const { viewer } = cesiumInstance
      this.cesiumInstance = cesiumInstance
      var scene = viewer.scene
      scene.debugShowFramesPerSecond = true
      this.cesiumInstance = cesiumInstance
      viewer.scene.globe.depthTestAgainstTerrain = true
    },
  },
}
</script>

<style scoped>
.demo-tool {
  position: absolute;
  top: 10px;
  left: 20px;
  z-index: 1000;
  border: 1px solid red;
}
</style>
```

### 预期输出

```
减少一个图层
```

### 实际输出

```
错误弹框
```

**Comment by zouyaoji** [comment]
@JennicaLi 重现不了呢。

https://user-images.githubusercontent.com/24430116/123778334-930a7f00-d903-11eb-8982-192cd4981494.mp4

**Comment by JennicaLi** [comment]
点击按钮后，再缩放下图层下试试呢
[动图](https://z3.ax1x.com/2021/06/30/RBCLEF.gif)

**Comment by zouyaoji** [comment]
也是好的。
https://z3.ax1x.com/2021/06/30/RBZZo6.gif

**Comment by JennicaLi** [comment]
请问cesium用的是哪个版本，我用的是'https://zouyaoji.top/vue-cesium/statics/SuperMapCesium/Cesium.js'

**Comment by zouyaoji** [comment]
哦  我用的原生Cesium测试的，你用的超图的WebGL？确实能重现问题了，回头换他们新版本试试看看。

**Comment by zouyaoji** [comment]
@JennicaLi 
2.2.5版本解决了此问题，试一下哈。

**Comment by zouyaoji** [comment]
vue-cesium@next的vue3版也重现了该问题，感谢反馈。
